services:
  my-mongodb:
    hostname: my-mongodb
    image: mongo:4.4
    container_name: my-mongodb
      #user: ${UID}:${GID}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_SERVER: ${MONGO_SERVER}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    command: mongod --port ${MONGO_PORT}
    links:
      - keycloak
    env_file: .env
    volumes:
      - ./volumes/mongo_data:/data/db:rw
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
        local_net:
            ipv4_address: 172.21.0.10

  mongo_seed:
    container_name: mongo_seed
    image: mongo:4.4
      #user: ${UID}:${GID}
    links:
      - my-mongodb
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_SERVER: ${MONGO_SERVER}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./mongo-seed:/mongo-seed
      - ./volumes/shared_data:/shared_data
      - ./front_end/openVRE/install:/install_data
    command:
      /mongo-seed/import.sh
    networks:
      - local_net
    depends_on:
      - my-mongodb

  
  vault-server:
    container_name: vault-server
    image: mapoferri/vault:1.13.333
    environment:
       VAULT_DEV_ROOT_TOKEN_ID: myroot
       VAULT_ADDR: "http://0.0.0.0:8200"
       VAULT_API_ADDR: "http://0.0.0.0:8200"
       VAULT_ADDRESS: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
      - "${VAULT_UI_PORT}:8080"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs:/vault/logs
      - ./vault/file:/vault/file
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/vault.json
    networks:
      #shared:
             local_net:
                ipv4_address: 172.21.0.18
    restart: always


  postgres:
    container_name: postgres
    image: postgres
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      local_net:
        ipv4_address: 172.21.0.13


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
        DB_VENDOR: ${DB_VENDOR}
        DB_ADDR: ${DB_ADDR}
        DB_DATABASE: ${DB_DATABASE}
        DB_USER: ${DB_USER}
        DB_SCHEMA: ${DB_SCHEMA}
        DB_PASSWORD: ${DB_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        PROXY_ADDRESS_FORWARDING: "false"
        #KEYCLOAK_FRONTEND_URL: "${FQDN_HOST_PROTOCOL}://${FQDN_HOST}:${KEYCLOAK_PORT}/auth"
        KEYCLOAK_FRONTEND_URL: "http://172.21.0.12:8080/auth"


    volumes:
        - ./keycloak/realms:/opt/jboss/keycloak/imports
    command:
            - '-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.migration.strategy=IGNORE_EXISTING'
    ports:
        - ${KEYCLOAK_PORT}:8080
    links:
        - postgres
    hostname: keycloak
    networks:
      local_net:
        ipv4_address: 172.21.0.12
    depends_on:
      - postgres

  front_end:
    container_name: front_end
    hostname: front_end.dockerized_vre_local_net
    build:
      context: ./front_end/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./front_end/act_qmaster:/var/lib/gridengine/default/common/act_qmaster
      - ./volumes/openVRE/tools:/var/www/html/openVRE/public/tools
      - ./front_end/openVRE/public/:/var/www/html/openVRE/public
      - ./front_end/openVRE/config:/var/www/html/openVRE/config
      - ./volumes/shared_data:/shared_data
    environment:
      - DOCKER_GROUP:${DOCKER_GROUP}
    links:
      - my-mongodb
      - keycloak
    depends_on:
      - sgecore
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      #shared:
              local_net:
                ipv4_address: 172.21.0.14

  sgecore:
    build:
          context: ./sge
    container_name: sgecore
    hostname: sgecore
    environment:
      - DOCKER_GROUP:${DOCKER_GROUP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rprivate
      - ./sge/configuration:/tmp/configuration:rprivate
      - ./sge/configuration:/etc/gridengine/configuration:rprivate
      - ./volumes/shared_data:/shared_data:rshared
    stdin_open: true
    networks:
      - local_net
    ports:
      - 6444:6444
    
    restart: always


networks:
  local_net:
    #Use on openStack cloud
    driver_opts:
      com.docker.network.driver.mtu: 1442
    ipam:
      config:
            - subnet: 172.21.0.0/24
