FROM httpd:2.4.33-alpine
#FROM httpd:2.4

RUN apk update; \
    apk upgrade; 
# Copy apache vhost file to proxy php requests to php-fpm container


COPY demo.apache.conf /usr/local/apache2/conf/demo.apache.conf

ENV WEB_DOCUMENT_ROOT=/var/www/

#EXPOSE 80 443

WORKDIR /var/www

